import { BranchConfig } from "./types";

export const aerovokzalnayaBranch: BranchConfig = {
  id: "aerovokzalnaya",
  name: "Аэровокзальная",
  address: "ул. Аэровокзальная, д. XX",
  color: "#A8E890",
  colorClass: "bg-[#A8E890]",
  accentColor: "#00ff60",
  isActive: true,
  zones: [
    {
      id: "normal",
      name: "Normal",
      nameRu: "Стандарт",
//      description: "Стандартная игровая зона",
      seats: 30,
      tariffs: [
        {
          id: "cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 159,
          priceWeekend: 179,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 399,
          priceWeekend: 449,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 639,
          priceWeekend: 719,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 799,
          priceWeekend: 899,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 899,
          priceWeekend: 989,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 1919,
          priceWeekend: 2159,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor1", name: "Monitor", nameRu: "Монитор #1", description: "ARDOR Eternity 27\" 240Hz" },
        { id: "monitor2", name: "Monitor", nameRu: "Монитор #2", description: "AOC Gaming 24'5\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Blade PRO" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "ARDOR Prime PRO" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4060", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "vip",
      name: "VIP",
      nameRu: "VIP",
//      description: "Стандартная игровая зона",
      seats: 10,
      tariffs: [
        {
          id: "vip-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 199,
          priceWeekend: 219,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "vip-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 499,
          priceWeekend: 549,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 799,
          priceWeekend: 879,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 999,
          priceWeekend: 1099,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1099,
          priceWeekend: 1209,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "vip-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 2399,
          priceWeekend: 2629,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "GIGABYTE 27\" 2K 240Hz OLED" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Immortality TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G Pro Hero" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 5070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "bootcamp",
      name: "Bootcamp",
      nameRu: "Bootcamp",
//      description: "Стандартная игровая зона",
      seats: 10,
      tariffs: [
        {
          id: "bootcamp-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 219,
          priceWeekend: 239,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "bootcamp-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 549,
          priceWeekend: 599,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 879,
          priceWeekend: 959,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1099,
          priceWeekend: 1199,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1209,
          priceWeekend: 1319,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "bootcamp-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 2629,
          priceWeekend: 2879,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor1", name: "Monitor", nameRu: "Монитор #1", description: "ViewSonic 2K-PRO 27\" 240Hz" },
        { id: "monitor2", name: "Monitor", nameRu: "Монитор #2", description: "ACER Nitro 24'5\" 390Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Maul" },
        { id: "mouse1", name: "Mouse", nameRu: "Мышь #1", description: "LAMZU Thorn" },
        { id: "mouse2", name: "Mouse", nameRu: "Мышь #2", description: "Logitech G Pro Hero" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-14600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 5070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "quadro",
      name: "Quadro",
      nameRu: "Quadro",
//      description: "Стандартная игровая зона",
      seats: 4,
      tariffs: [
        {
          id: "quadro-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 239,
          priceWeekend: 259,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "quadro-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 599,
          priceWeekend: 649,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "quadro-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 959,
          priceWeekend: 1039,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "quadro-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1199,
          priceWeekend: 1299,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "quadro-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1319,
          priceWeekend: 1429,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "quadro-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 2879,
          priceWeekend: 3119,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "ARDOR Eternity 27\" 2K 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Immortality TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G Pro Hero" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "trio",
      name: "Trio",
      nameRu: "Trio",
//      description: "Стандартная игровая зона",
      seats: 3,
      tariffs: [
        {
          id: "trio-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 259,
          priceWeekend: 279,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "trio-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 649,
          priceWeekend: 699,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "trio-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1039,
          priceWeekend: 1119,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "trio-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1299,
          priceWeekend: 1399,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "trio-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1429,
          priceWeekend: 1539,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "trio-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 3119,
          priceWeekend: 3359,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "AOC Gaming 24'5\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Immortality TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G Pro Hero" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 5070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "duo",
      name: "Duo",
      nameRu: "Duo",
//      description: "Стандартная игровая зона",
      seats: 4,
      tariffs: [
        {
          id: "duo-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 279,
          priceWeekend: 299,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "duo-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 699,
          priceWeekend: 749,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "duo-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1119,
          priceWeekend: 1199,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "duo-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1399,
          priceWeekend: 1499,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "duo-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1539,
          priceWeekend: 1649,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "duo-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 3359,
          priceWeekend: 3599,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor1", name: "Monitor", nameRu: "Монитор #1", description: "AOC Gaming 24'5\" 240Hz" },
        { id: "monitor2", name: "Monitor", nameRu: "Монитор #2", description: "ARDOR Eternity 27\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Maul" },
        { id: "mouse1", name: "Mouse", nameRu: "Мышь #1", description: "LAMZU Thorn" },
        { id: "mouse2", name: "Mouse", nameRu: "Мышь #2", description: "Logitech G Pro Hero" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "solo",
      name: "Solo",
      nameRu: "Solo",
//      description: "Стандартная игровая зона",
      seats: 1,
      tariffs: [
        {
          id: "solo-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 299,
          priceWeekend: 319,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "solo-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 749,
          priceWeekend: 799,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "solo-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1199,
          priceWeekend: 1279,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "solo-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1499,
          priceWeekend: 1599,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "solo-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1649,
          priceWeekend: 1759,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "solo-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 3599,
          priceWeekend: 3839,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "ACER Nitro 24'5\" 390Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Maul" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "LAMZU Thorn" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "stream",
      name: "Stream",
      nameRu: "Stream",
//      description: "Стандартная игровая зона",
      seats: 1,
      tariffs: [
        {
          id: "stream-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 319,
          priceWeekend: 339,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "stream-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 799,
          priceWeekend: 849,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "stream-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1279,
          priceWeekend: 1359,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "stream-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1599,
          priceWeekend: 1699,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "stream-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1759,
          priceWeekend: 1869,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "stream-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 3839,
          priceWeekend: 4079,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor1", name: "Monitor", nameRu: "Монитор #1", description: "MSI 27\" 360Hz QD-OLED" },
        { id: "monitor2", name: "Monitor", nameRu: "Монитор #2", description: "ASUS 27\" 144Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Wakizashi" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "LAMZU Thorn" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
        { id: "camera", name: "Camera", nameRu: "Камера", description: "Logitech Brio Stream 4K" },
        { id: "microphone", name: "Microphone", nameRu: "Микрофон", description: "HyperX Quadcast S" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i7-13700F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4080", category: "gpu" },
        { id: "ram", name: "RAM", value: "64GB", category: "ram" },
      ],
    },
    {
      id: "tv",
      name: "TV",
      nameRu: "TV зона",
      description: "До 2-х человек на TV",
      seats: 4,
      tariffs: [
        {
          id: "tv-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 399,
          priceWeekend: 449,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "tv-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 999,
          priceWeekend: 1129,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1599,
          priceWeekend: 1799,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1999,
          priceWeekend: 2249,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
      ],
      peripherals: [
        { id: "controller", name: "Controller", nameRu: "Геймпад", description: "PS5 DualSense x2 (на консоль)" },
      ],
      components: [
        { id: "console", name: "Консоль", value: "PlayStation 5", category: "other" },
        { id: "tv", name: "TV", value: "55\"", category: "monitor" },
      ],
    },
  ],
};
