import { BranchConfig } from "./types";

export const kirenskogoBranch: BranchConfig = {
  id: "kirenskogo",
  name: "Киренского",
  address: "ул. Киренского, д. 43",
  color: "#FF6B6B",
  colorClass: "bg-[#FF6B6B]",
  isActive: true,
  zones: [
    {
      id: "normal",
      name: "Normal",
      nameRu: "Стандарт",
//       description: "Стандартная игровая зона",
      seats: 15,
      tariffs: [
        {
          id: "cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 159,
          priceWeekend: 179,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 399,
          priceWeekend: 449,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 639,
          priceWeekend: 719,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 20:00 до 8:00",
          priceWeekday: 799,
          priceWeekend: 899,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 899,
          priceWeekend: 989,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //       description: "24/7",
          priceWeekday: 1919,
          priceWeekend: 2159,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "BenQ Zowie 24'5\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "Redragon Ucal Pro" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G102 LightSync" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4060", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "vip",
      name: "VIP",
      nameRu: "VIP",
//       description: "VIP зона с улучшенным оборудованием",
      seats: 10,
      tariffs: [
        {
          id: "vip-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 199,
          priceWeekend: 219,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "vip-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 499,
          priceWeekend: 549,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 799,
          priceWeekend: 879,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 999,
          priceWeekend: 1099,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1099,
          priceWeekend: 1209,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "vip-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //       description: "24/7",
          priceWeekday: 2399,
          priceWeekend: 2629,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "GIGABYTE 27\" 2K 240Hz OLED" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "Redragon Elf Pro" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G403 Hero" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "bootcamp",
      name: "Bootcamp",
      nameRu: "Буткемп",
//       description: "Профессиональная игровая зона для команд",
      seats: 5,
      tariffs: [
        {
          id: "bootcamp-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 219,
          priceWeekend: 239,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "bootcamp-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 549,
          priceWeekend: 599,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 879,
          priceWeekend: 959,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1099,
          priceWeekend: 1199,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1209,
          priceWeekend: 1319,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "bootcamp-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //       description: "24/7",
          priceWeekday: 2629,
          priceWeekend: 2879,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "BenQ Zowie 24'5\" 360Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "Dark Project KD87A" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "BenQ Zowie S1" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha S" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 5070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "tv",
      name: "TV",
      nameRu: "TV зона",
      description: "До 3-х человек на TV",
      seats: 6,
      tariffs: [
        {
          id: "tv-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 349,
          priceWeekend: 399,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "tv-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 879,
          priceWeekend: 999,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1399,
          priceWeekend: 1599,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1749,
          priceWeekend: 1999,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
      ],
      peripherals: [
        { id: "controller", name: "Controller", nameRu: "Геймпад", description: "PS5 DualSense x2 (на консоль)" },
      ],
      components: [
        { id: "console", name: "Консоль", value: "PlayStation 5", category: "other" },
        { id: "tv", name: "TV", value: "65\" ", category: "monitor" },
      ],
    },
  ],
};
