import { BranchConfig } from "./types";

export const lomakoBranch: BranchConfig = {
  id: "lomako",
  name: "Ломако",
  address: "ул. Петра Ломако, д. 4",
  color: "#FFFFFF",
  colorClass: "bg-[#FFFFFF]",
  isActive: true,
  zones: [
    {
      id: "normal",
      name: "Normal",
      nameRu: "Стандарт",
//       description: "Стандартная игровая зона",
      seats: 8,
      tariffs: [
        {
          id: "cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 139,
          priceWeekend: 159,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 349,
          priceWeekend: 399,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 559,
          priceWeekend: 639,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 20:00 до 8:00",
          priceWeekday: 699,
          priceWeekend: 799,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 799,
          priceWeekend: 899,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //       description: "24/7",
          priceWeekday: 1679,
          priceWeekend: 1919,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor1", name: "Monitor", nameRu: "Монитор #1", description: "AOC 24'5\" (FHD) 240Hz" },
        { id: "monitor2", name: "Monitor", nameRu: "Монитор #2", description: "MSI MAG 24'5\" (FHD) 300Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "Logitech G413 TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G102 LightSync" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-10400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 3060", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "vip",
      name: "VIP",
      nameRu: "VIP",
//       description: "VIP зона с улучшенным оборудованием",
      seats: 11,
      tariffs: [
        {
          id: "vip-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 179,
          priceWeekend: 199,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "vip-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 449,
          priceWeekend: 499,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 719,
          priceWeekend: 799,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 899,
          priceWeekend: 999,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 989,
          priceWeekend: 1099,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "vip-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //       description: "24/7",
          priceWeekday: 2159,
          priceWeekend: 2399,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "AOC 27\" (FHD) 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Immortality TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "ARDOR Prime PRO" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-10400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4060", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "2k",
      name: "2k",
      nameRu: "2k",
//       description: "Профессиональная игровая зона для команд",
      seats: 5,
      tariffs: [
        {
          id: "2k-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 199,
          priceWeekend: 219,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "2k-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 499,
          priceWeekend: 549,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "2k-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 799,
          priceWeekend: 879,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "2k-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 999,
          priceWeekend: 1099,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "2k-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1099,
          priceWeekend: 1209,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "2k-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //       description: "24/7",
          priceWeekday: 2399,
          priceWeekend: 2629,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "MSI MAG 27\" (2K) 320Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "AULA HERO 84HE" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "AJAZZ Apex" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "bootcamp",
      name: "Bootcamp",
      nameRu: "Bootcamp",
//       description: "Профессиональная игровая зона для команд",
      seats: 5,
      tariffs: [
        {
          id: "bootcamp-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 199,
          priceWeekend: 219,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "bootcamp-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 499,
          priceWeekend: 549,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 799,
          priceWeekend: 879,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 999,
          priceWeekend: 1099,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "bootcamp-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1099,
          priceWeekend: 1209,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "bootcamp-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //       description: "24/7",
          priceWeekday: 2399,
          priceWeekend: 2629,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "ACER Nitro 24'5\" (FHD) 390Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ZONE 51 CITRIN" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "BenQ Zowie S1" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-10400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4070", category: "gpu" },
        { id: "ram", name: "RAM", value: "64GB", category: "ram" },
      ],
    },
    {
      id: "tv",
      name: "TV",
      nameRu: "TV зона",
       description: "До 3-х человек на TV",
      seats: 6,
      tariffs: [
        {
          id: "tv-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 349,
          priceWeekend: 399,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "tv-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 879,
          priceWeekend: 999,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1399,
          priceWeekend: 1599,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1749,
          priceWeekend: 1999,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
      ],
      peripherals: [
        { id: "controller", name: "Controller", nameRu: "Геймпад", description: "PS5 DualSense x2 (на консоль)" },
      ],
      components: [
        { id: "console", name: "Консоль", value: "PlayStation 5", category: "other" },
        { id: "tv", name: "TV", value: "55\" ", category: "monitor" },
      ],
    },
  ],
};
