import { BranchConfig } from "./types";

export const molokovaBranch: BranchConfig = {
  id: "molokova",
  name: "Молокова",
  address: "ул. Молокова, д. 21",
  color: "#FFD93D",
  colorClass: "bg-[#FFD93D]",
  isActive: true,
  zones: [
    {
      id: "normal",
      name: "Normal",
      nameRu: "Стандарт",
//      description: "Стандартная игровая зона",
      seats: 10,
      tariffs: [
        {
          id: "cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 139,
          priceWeekend: 159,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 349,
          priceWeekend: 399,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 559,
          priceWeekend: 639,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 699,
          priceWeekend: 799,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 799,
          priceWeekend: 899,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 1679,
          priceWeekend: 1919,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor1", name: "Monitor", nameRu: "Монитор #1", description: "AOC Gaming 27\" 165Hz" },
        { id: "monitor2", name: "Monitor", nameRu: "Монитор #2", description: "AOC Gaming 24'5\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "Red Square Keyrox TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G102 LightSync" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Core 7.1" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-10400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 3070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "mid",
      name: "MID",
      nameRu: "MID",
//      description: "VIP зона с улучшенным оборудованием",
      seats: 5,
      tariffs: [
        {
          id: "mid-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 159,
          priceWeekend: 179,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "mid-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 399,
          priceWeekend: 449,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "mid-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 639,
          priceWeekend: 719,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "mid-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 799,
          priceWeekend: 899,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "mid-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 899,
          priceWeekend: 989,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "mid-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 1919,
          priceWeekend: 2159,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "ARDOR Eternity 27\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ZONE 51 ADAMANT TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "ARDOR Prime PRO" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Core 7.1" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-10400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4060 Ti", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "vip",
      name: "VIP",
      nameRu: "VIP",
//      description: "VIP зона с улучшенным оборудованием",
      seats: 5,
      tariffs: [
        {
          id: "vip-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 179,
          priceWeekend: 199,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "vip-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 449,
          priceWeekend: 499,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 719,
          priceWeekend: 799,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 899,
          priceWeekend: 999,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 989,
          priceWeekend: 1099,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "vip-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 2159,
          priceWeekend: 2399,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "AOC 27\" (FHD) 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Immortality TKL" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "Logitech G403 Hero" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-10600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4060 Ti", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "solo",
      name: "Solo",
      nameRu: "Solo",
//      description: "VIP зона с улучшенным оборудованием",
      seats: 1,
      tariffs: [
        {
          id: "solo-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 279,
          priceWeekend: 299,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "solo-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 699,
          priceWeekend: 749,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "solo-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1119,
          priceWeekend: 1199,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "solo-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1399,
          priceWeekend: 1499,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "solo-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1539,
          priceWeekend: 1649,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "solo-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
          description: "24/7",
          priceWeekday: 3359,
          priceWeekend: 3599,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "Viewsonic 2K-PRO 27\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "ARDOR Maul" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "AJAZZ Apex" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud III" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13600KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 5070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "tv",
      name: "TV",
      nameRu: "TV зона",
       description: "До 3-х человек на TV",
      seats: 3,
      tariffs: [
        {
          id: "tv-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 349,
          priceWeekend: 399,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "tv-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 879,
          priceWeekend: 999,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1399,
          priceWeekend: 1599,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1749,
          priceWeekend: 1999,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
      ],
      peripherals: [
        { id: "controller", name: "Controller", nameRu: "Геймпад", description: "PS5 DualSense x2 (на консоль)" },
      ],
      components: [
        { id: "console", name: "Консоль", value: "PlayStation 5", category: "other" },
        { id: "tv", name: "TV", value: "70\" ", category: "monitor" },
      ],
    },
  ],
};
