import { BranchConfig } from "./types";

export const muzhestvaBranch: BranchConfig = {
  id: "muzhestva",
  name: "Мужества",
  address: "ул. Мужества, д. 24",
  color: "#4A9EFF",
  colorClass: "bg-[#4A9EFF]",
  isActive: true,
  zones: [
    {
      id: "normal",
      name: "Normal",
      nameRu: "Стандарт",
//      description: "Стандартная игровая зона",
      seats: 10,
      tariffs: [
        {
          id: "cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 139,
          priceWeekend: 159,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 349,
          priceWeekend: 399,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 559,
          priceWeekend: 639,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 699,
          priceWeekend: 799,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 799,
          priceWeekend: 899,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //      description: "24/7",
          priceWeekday: 1679,
          priceWeekend: 1919,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "ACER 24'5\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "Redragon Elf" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "ARDOR Prime PRO" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i9-11900", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 3060", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "vip",
      name: "VIP",
      nameRu: "VIP",
//      description: "VIP зона с улучшенным оборудованием",
      seats: 10,
      tariffs: [
        {
          id: "vip-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 179,
          priceWeekend: 199,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "vip-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 449,
          priceWeekend: 499,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 719,
          priceWeekend: 799,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 899,
          priceWeekend: 999,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 999,
          priceWeekend: 1099,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "vip-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //      description: "24/7",
          priceWeekday: 2159,
          priceWeekend: 2399,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "ARDOR Eternity 27\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "HyperX Origins Core" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "BenQ Zowie S1" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i7-10700KF", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 4060 Ti", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "2k",
      name: "2k",
      nameRu: "2k",
//      description: "VIP зона с улучшенным оборудованием",
      seats: 4,
      tariffs: [
        {
          id: "2k-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 199,
          priceWeekend: 219,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "vip-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 499,
          priceWeekend: 549,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 799,
          priceWeekend: 879,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 999,
          priceWeekend: 1099,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "vip-cyber-day",
          name: "Cyber Day",
          nameRu: "Кибер день",
          duration: 600,
          description: "с 10:00 до 20:00",
          priceWeekday: 1099,
          priceWeekend: 1209,
          availableFrom: 10,
          availableTo: 14,
          perMinute: false,
          displayOnly: true,
        },
        {
          id: "vip-cyber-24",
          name: "Cyber 24",
          nameRu: "Кибер сутки",
          duration: 1440,
    //      description: "24/7",
          priceWeekday: 2399,
          priceWeekend: 2629,
          perMinute: false,
          displayOnly: true,
        },
      ],
      peripherals: [
        { id: "monitor", name: "Monitor", nameRu: "Монитор", description: "ViewSonic 2K-PRO 27\" 240Hz" },
        { id: "keyboard", name: "Keyboard", nameRu: "Клавиатура", description: "AULA HERO 84HE" },
        { id: "mouse", name: "Mouse", nameRu: "Мышь", description: "AJAZZ Apex" },
        { id: "headset", name: "Headset", nameRu: "Наушники", description: "HyperX Cloud Alpha" },
      ],
      components: [
        { id: "cpu", name: "CPU", value: "Intel Core i5-13400F", category: "cpu" },
        { id: "gpu", name: "GPU", value: "NVIDIA RTX 5070", category: "gpu" },
        { id: "ram", name: "RAM", value: "32GB", category: "ram" },
      ],
    },
    {
      id: "tv",
      name: "TV",
      nameRu: "TV зона",
       description: "До 2-х человек на TV",
      seats: 2,
      tariffs: [
        {
          id: "tv-cyber-hour",
          name: "Cyber Hour",
          nameRu: "Кибер час",
          duration: 60,
          description: "Поминутная оплата",
          priceWeekday: 349,
          priceWeekend: 399,
          perMinute: true,
          displayOnly: false,
        },
        {
          id: "tv-triple-kill",
          name: "Triple Kill",
          nameRu: "Трипл килл",
          duration: 180,
          priceWeekday: 879,
          priceWeekend: 999,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-ultra-kill",
          name: "Ultra Kill",
          nameRu: "Ультра килл",
          duration: 300,
          priceWeekday: 1399,
          priceWeekend: 1599,
          perMinute: false,
          displayOnly: false,
        },
        {
          id: "tv-cyber-night",
          name: "Cyber Night",
          nameRu: "Кибер ночь",
          duration: 600,
          description: "с 22:00 до 8:00",
          priceWeekday: 1749,
          priceWeekend: 1999,
          availableFrom: 22,
          availableTo: 3,
          perMinute: false,
          displayOnly: false,
        },
      ],
      peripherals: [
        { id: "controller", name: "Controller", nameRu: "Геймпад", description: "PS5 DualSense x2 (на консоль)" },
      ],
      components: [
        { id: "console", name: "Консоль", value: "PlayStation 5", category: "other" },
        { id: "tv", name: "TV", value: "49\" ", category: "monitor" },
      ],
    },
  ],
};
